# Generated by Django 4.2.7 on 2023-12-10 09:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utiles


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام برند')),
                ('image', models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Features_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار ویژگی')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.features', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های های محصول',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام گروه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال بودن')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('logged_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='products.groups', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال بودن')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('logged_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('brands', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productBrand', to='products.brands', verbose_name='برند')),
                ('features', models.ManyToManyField(through='products.Features_Products', to='products.features')),
                ('groups', models.ManyToManyField(related_name='productGroup', to='products.groups', verbose_name='گروه کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.CreateModel(
            name='Product_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویرها',
            },
        ),
        migrations.AddField(
            model_name='features_products',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='features',
            name='groups',
            field=models.ManyToManyField(related_name='featureGroup', to='products.groups', verbose_name='گروه'),
        ),
    ]
