# Generated by Django 4.2.7 on 2023-12-10 13:15

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='groups',
            new_name='product_groups',
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product_gallery',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
    ]
