# Generated by Django 4.2.7 on 2023-12-13 19:24

from django.db import migrations, models
import django.db.models.deletion
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_groups_products_product_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brands',
            new_name='product_brands',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='features',
            new_name='product_features',
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='features_products',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productFeature', to='products.features', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product_gallery',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
    ]
