# Generated by Django 4.2.7 on 2023-12-14 13:16

from django.db import migrations, models
import django.db.models.deletion
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brands_image_alter_brands_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='خلاصه توضیحات'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='features_products',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.features', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='features_products',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productFeature', to='products.products', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product_gallery',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
    ]
