# Generated by Django 4.2.7 on 2023-12-14 13:18

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_short_description_alter_brands_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='خلاصه توضیحات'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product_gallery',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
    ]
