# Generated by Django 4.2.7 on 2024-01-18 17:25

from django.db import migrations, models
import django.db.models.deletion
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_brands_image_alter_groups_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='title',
            field=models.CharField(max_length=50, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='feature_value',
            name='value_title',
            field=models.CharField(max_length=100, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='features',
            name='title',
            field=models.CharField(max_length=100, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='features_products',
            name='filter_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productFeature_featureValue', to='products.feature_value', verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='features_products',
            name='value',
            field=models.CharField(max_length=100, verbose_name='مقدار ویژگی (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='title',
            field=models.CharField(max_length=50, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='product_gallery',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=250, verbose_name='نام کالا'),
        ),
    ]
