# Generated by Django 4.2.7 on 2024-02-22 16:03

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_brands_image_alter_groups_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product_gallery',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر'),
        ),
    ]
