"""
Django settings for online_shopping project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aefkwsgg8ifb@8^nj#ke0k((+cf0w=4u5!k$=mlfh%hdc@4!t^'
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ALLOWED_HOSTS = []

# DEBUG = False
# ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'apps.main.apps.MainConfig',
    'apps.accounting.apps.AccountingConfig',
    'apps.products.apps.ProductsConfig',
    'apps.shop_cart.apps.ShopCartConfig',
    'apps.discount.apps.DiscountConfig',
    'apps.payments.apps.PaymentsConfig',
    'apps.warehouse.apps.WarehouseConfig',
    'apps.hub.apps.HubConfig',

    'django_admin_listfilter_dropdown',
    'django_render_partial',
    'django.contrib.humanize',
    'ckeditor_uploader',
    'ckeditor',
    'django_filters',
     
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.middlewares.RequestMiddleWare'
]

ROOT_URLCONF = 'online_shopping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.views.worldwide_content'
            ],
        },
    },
]

WSGI_APPLICATION = 'online_shopping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': env('ENGINE_NAME'),
        'NAME': env('DB_NAME'),
        'HOST':  env('DB_HOST'),
        'PORT':  env('DB_PORT'),
        'USER':  env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
    }
}

# mysqldump -u root -p online_shopping > backup.sql


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

# USE_TZ = True ***


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(os.path.join(BASE_DIR, 'static/'),)

MEDIA_URL = '/media/'
MEDIA_ROOT= os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL="accounting.CustomUser"


#============================================================================

CKEDITOR_UPLOAD_PATH = 'images/ckeditor/upload_files/'
CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
CKEDITOR_CONFIGS = {
    'default':
        {
            'toolbar': 'Custom',
            'toolbar_Custom': [
                ['Bold','Link','Unlink','Image'],
                
            ],
        },
    'special':
        {
            'toolbar': 'Special', 'height': 500,
            'toolbar': 'full',
            'toolbar_Special':
                [
                   ['Bold','Link','Unlink','Image'],
                   ['CodeSnippet'], 
                ], 'extraPlugins': ','.join(['codesnippet','clipboard',]) 
        },
    'special_an':
        {'toolbar': "Special", 'height':500,
         'toolbar_Special':
             [
                 ['Bold'],
                 ['CodeSnippet'], 
             ], 'extraPlugins': ','.join(['codesnippet',]) 
         }
}


#============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'FerdowsGardenMuseum@gmail.com'
EMAIL_HOST_PASSWORD = 'pjuxnqkxyknrbyrw'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# LOGIN_REDIRECT_URL = "home"
# LOGOUT_REDIRECT_URL = "home"
