# Generated by Django 4.2.7 on 2024-02-20 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_alter_brands_image_alter_groups_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('logged_date', models.DateTimeField(auto_now_add=True, verbose_name='تارخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال بودن')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Admin', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Parent', to='hub.comments')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commetnt_Product', to='products.products', verbose_name='کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_User', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
