# Generated by Django 4.2.7 on 2024-02-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='logged_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='logged_date',
            new_name='created_at',
        ),
    ]
