# Generated by Django 4.2.7 on 2024-02-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0027_alter_brands_image_alter_groups_image_and_more'),
        ('hub', '0004_rename_logged_date_comments_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تارخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlist_Product', to='products.products', verbose_name='کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlist_User', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
            },
        ),
    ]
