# Generated by Django 4.2.7 on 2024-02-04 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0016_alter_brands_image_alter_groups_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سبد تخفیف')),
                ('discount_basket_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('expiry_date', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'سبد تخفیف',
                'verbose_name_plural': 'سبدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('expiry_date', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='DiscountBasketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountBasket', to='discount.discountbasket', verbose_name='سبد تخفیف')),
                ('discount_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountProducts', to='products.products', verbose_name='کالاهای تخفیف دار')),
            ],
            options={
                'verbose_name': 'جزییات سبد تخفیف',
            },
        ),
    ]
