# Generated by Django 4.2.7 on 2024-02-04 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='discount_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='کد تخفیف'),
        ),
    ]
