# Generated by Django 4.2.7 on 2024-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discounts_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='discount_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد تخفیف'),
        ),
    ]
