# Generated by Django 4.2.7 on 2023-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_customuser_cell_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('rather not to say', 'اعلام نکردن'), ('male', 'آقا'), ('female', 'خانم')], default='rather not to say', max_length=50, null=True),
        ),
    ]
