# Generated by Django 4.2.7 on 2023-12-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='is_admin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_customer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
