# Generated by Django 4.2.7 on 2023-12-08 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_permission_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='وضعیت ابرکارمند بودن'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='وضعیت کارمند بودن'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='وضعیت مشتری بودن'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='دسترسی', to=settings.AUTH_USER_MODEL),
        ),
    ]
