# Generated by Django 4.2.7 on 2023-12-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_permission_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_customer',
        ),
    ]
