# Generated by Django 4.2.7 on 2023-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_permission_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_admin',
        ),
    ]
