# Generated by Django 4.2.7 on 2023-12-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_permission_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
