# Generated by Django 4.2.7 on 2023-12-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_rename_is_staff_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
