# Generated by Django 4.2.7 on 2023-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='وضعیت کارمند بودن'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='وضعیت ابرکارمند بودن'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
