# Generated by Django 4.2.7 on 2024-01-22 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_customuser_is_admin_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر پروفایل')),
            ],
        ),
    ]
