# Generated by Django 4.2.7 on 2024-01-22 12:13

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر پروفایل'),
        ),
    ]
