# Generated by Django 4.2.7 on 2024-01-29 10:17

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر پروفایل'),
        ),
    ]
