# Generated by Django 4.2.7 on 2024-02-01 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_customer_phone_num_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نام مشتری'),
        ),
    ]
