# Generated by Django 4.2.7 on 2024-02-01 17:43

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_customer_address_alter_customer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر پروفایل'),
        ),
    ]
