# Generated by Django 4.2.7 on 2024-02-04 12:14

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utiles.Uploading_Files.file_name, verbose_name='تصویر پروفایل'),
        ),
    ]
