# Generated by Django 4.2.7 on 2024-02-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'انبار', 'verbose_name_plural': 'انبار'},
        ),
        migrations.AlterModelOptions(
            name='warehouse_types',
            options={'verbose_name': 'نوع انبار', 'verbose_name_plural': 'نوع انبار'},
        ),
        migrations.AlterField(
            model_name='warehouse_types',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
