# Generated by Django 4.2.7 on 2024-02-05 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0026_alter_customer_image'),
        ('shop_cart', '0006_alter_orders_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('amount_paid', models.IntegerField(verbose_name='مبلغ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='کد وضیت پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری')),
                ('logged_date', models.DateTimeField(default=datetime.datetime(2024, 2, 5, 18, 26, 12, 536183), verbose_name='تاریخ ثبت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('payment_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsCustomer', to='accounting.customer', verbose_name='مشتری')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentOrder', to='shop_cart.orders', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
