# Generated by Django 4.2.7 on 2024-02-17 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='logged_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
    ]
