# Generated by Django 4.2.7 on 2024-01-22 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_alter_brands_image_alter_groups_image_and_more'),
        ('accounting', '0014_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='شیوه پرداخت')),
            ],
            options={
                'verbose_name': 'شیوه پرداخت',
                'verbose_name_plural': 'شیوه های پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('logged_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد سفارش')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_Customer', to='accounting.customer', verbose_name='مشتری')),
                ('order_payment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_Payment', to='shop_cart.payment_types', verbose_name='شیوه پرداخت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='Details_Of_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='مبلغ')),
                ('details_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_Order', to='shop_cart.orders', verbose_name='سفارش')),
                ('details_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_Product', to='products.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزییات سفارش',
                'verbose_name_plural': 'جزِییات سفارش ها',
            },
        ),
    ]
