# Generated by Django 4.2.7 on 2024-02-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0005_alter_orders_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_payment',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_Payment', to='shop_cart.payment_types', verbose_name='شیوه پرداخت'),
        ),
    ]
