# Generated by Django 4.2.7 on 2024-02-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0006_alter_orders_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OederState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'وضعیت صفارش',
                'verbose_name_plural': 'انواع وضعیت سفارش',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='order_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_State', to='shop_cart.oederstate', verbose_name='وضعیت سفارش'),
        ),
    ]
