# Generated by Django 4.2.7 on 2024-02-29 12:29

from django.db import migrations, models
import django.utils.timezone
import utiles


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='تیتر یک')),
                ('heading_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='تیتر دو')),
                ('heading_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='تیتر سه')),
                ('image', models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='اسلایدر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فغال بودن')),
                ('craete_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
