# Generated by Django 4.2.7 on 2024-03-02 09:53

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='اسلایدر'),
        ),
    ]
