# Generated by Django 4.2.7 on 2024-03-02 09:53

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_slider_link_slider_slider_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='اسلایدر'),
        ),
    ]
