# Generated by Django 4.2.7 on 2024-03-02 09:55

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_link',
            new_name='link_slider',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='اسلایدر'),
        ),
    ]
