# Generated by Django 4.2.7 on 2025-08-11 15:29

from django.db import migrations, models
import utiles


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_slider_link_slider_link_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=utiles.Uploading_Files.file_name, verbose_name='اسلایدر'),
        ),
    ]
